apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  shareProcessNamespace: true
  #hostNetwork: true
  #hostIPC: true
  #hostPID: true
  containers:
    - name: nginx
      image: nginx:1.20.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: shell
      image: busybox
      stdin: true
      tty: true
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
